### ISSUE TITLE
If function returns defer.promise and it calls "notify" tasks are executing all together one by one with no respect to weightLimit

### ISSUE THREAD

**Issue by dimik** [dfilatov/vow-queue#17]
[Test case](https://github.com/dimik/vow-queue/blob/master/test/queue.js#L268)

**Comment by dfilatov** [comment]
Actually there's bug inside vow, not vow-queue

**Comment by dfilatov** [comment]
Fixed in vow 0.4.17 and vow-queue 0.4.3
